Add stage to check the test pipeline has completed.

diff --git a/jenkins-pipelines/openshift/Jenkinsfile b/jenkins-pipelines/openshift/Jenkinsfile
--- a/jenkins-pipelines/openshift/Jenkinsfile
+++ b/jenkins-pipelines/openshift/Jenkinsfile
@@ -191,6 +191,22 @@ node ('openstack-jenkins-slave') {
             """)
         }
 
+        stage('Check Jenkins test-pipeline has finished') {
+            sh("""
+                REQUEST=$(curl "https://jenkins-test-pipeline.\$DOMAIN_SUFFIX/job/test-pipeline/job/test-pipeline-openshift-test-pipeline/lastBuild/api/json?tree=result" | jq ".result")
+                while [ \$REQUEST -ne "SUCCESS" ]; do
+                    # Check that the build status isn't either FAILURE or ABORTED.
+                    ACCEPTABLE=(FAILURE ABORTED)
+                    if [[ \$ACCEPTABLE[@] =~ \$REQUEST ]]; then
+                        echo "Test-pipeline failed!" 1>&2
+                        exit 1
+                    fi
+                    sleep 10
+                    \$REQUEST
+                done
+            """)
+        }
+
         //slackSend color: 'good', message: "Pipeline build Completed Successfully: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
 
     } catch (e) {
