Keystone v3 new pipeline version (#31)
* vars added for v3.11

* corrected error

* changed branches

* removed stupid plugin

* stupid comment characters

* fixed reg vars

* heat branch changed to v3.11

* added heat cleanup and exception print

* changed heat version to force failure (test exception print)

* removed exception print and forced failure

* Enabled slack notifications

* Update jenkins-pipelines/openshift/Jenkinsfile

Co-Authored-By: koneill94 <35918022+koneill94@users.noreply.github.com>

* Bastion fix branch added for testing

* updated heat and ansible branches to v3.11

* Update jenkins-pipelines/openshift/Jenkinsfile

* Update jenkins-pipelines/openshift/Jenkinsfile

* Update jenkins-pipelines/openshift/Jenkinsfile

* Update Jenkinsfile

* Update Jenkinsfile

* Update Jenkinsfile

* Set branches

* an attempt to make it keystonev3

* an attempt to make it keystonev3

* Revert to v3.11 branch and remove AUTH URL hardcoding ready for pull request

diff --git a/jenkins-pipelines/openshift/Jenkinsfile b/jenkins-pipelines/openshift/Jenkinsfile
--- a/jenkins-pipelines/openshift/Jenkinsfile
+++ b/jenkins-pipelines/openshift/Jenkinsfile
@@ -1,9 +1,9 @@
 node ('openstack-jenkins-slave') {
     try {
-        def openshiftHeatBranch = 'master'
-        def openshiftDeploymentAnsibleBranch = 'master'
+        def openshiftHeatBranch = 'v3.11'
+        def openshiftDeploymentAnsibleBranch = 'v3.11'
 
-        slackSend color: 'good', message: "Pipeline build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
+        //slackSend color: 'good', message: "Pipeline build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
 
         stage('code-checkout') {
             git branch:"$openshiftHeatBranch", url:"https://github.com/UKCloud/openshift-heat.git"
@@ -17,8 +17,10 @@ node ('openstack-jenkins-slave') {
             sh "echo -e \"  rhn_activationkey: `oc get secrets rhelsubscriptions --template='{{ .data.rhel_activation_key }}' | base64 --decode`\" | tee -a rhel_reg_creds.yaml"
             sh "echo -e \"  satellite_fqdn: `oc get secrets rhelsubscriptions --template='{{ .data.satellite_fqdn }}' | base64 --decode`\" | tee -a rhel_reg_creds.yaml"
             sh "echo -e \"  satellite_deploy: `oc get secrets rhelsubscriptions --template='{{ .data.satellite_deploy }}' | base64 --decode`\" | tee -a rhel_reg_creds.yaml"
-            sh "echo export OS_TENANT_ID=`oc get configmap openstack-config --template='{{ .data.openstack_project_id }}'` | tee -a openstack_rc.sh"
-            sh "echo export OS_TENANT_NAME=`oc get configmap openstack-config --template='{{ .data.openstack_project_name }}'` | tee -a openstack_rc.sh"
+            sh "echo export OS_PROJECT_ID=`oc get configmap openstack-config --template='{{ .data.openstack_project_id }}'` | tee -a openstack_rc.sh"
+            sh "echo export OS_PROJECT_NAME=`oc get configmap openstack-config --template='{{ .data.openstack_project_name }}'` | tee -a openstack_rc.sh"
+            sh "echo export OS_USER_DOMAIN_NAME=Default | tee -a openstack_rc.sh"
+            sh "export OS_PROJECT_DOMAIN_ID=default | tee -a openstack_rc.sh"
             sh "echo export OS_AUTH_URL=`oc get configmap openstack-config --template='{{ .data.openstack_url }}'` | tee -a openstack_rc.sh"
             sh "echo export S3_ACCESS_KEY=`oc get secrets s3parameters --template='{{ .data.s3accesskey }}' | base64 --decode` | tee -a openstack_rc.sh"
             sh "echo export S3_SECRET_KEY=`oc get secrets s3parameters --template='{{ .data.s3secretkey }}' | base64 --decode` | tee -a openstack_rc.sh"
@@ -40,10 +42,13 @@ node ('openstack-jenkins-slave') {
             sh "echo export NODE_ROUTES=`oc get secrets openshift --template='{{ .data.node_routes }}' | base64 --decode` | tee -a openstack_rc.sh"
             sh "echo export MULTINETWORK=`oc get secrets openshift --template='{{ .data.multinetwork }}' | base64 --decode` | tee -a openstack_rc.sh"
             sh "echo export DEPLOYEXTRAGATEWAY=`oc get secrets openshift --template='{{ .data.deploy_extra_gateway }}' | base64 --decode` | tee -a openstack_rc.sh"
+            sh "echo export REG_URL=`oc get secrets openshift --template='{{ .data.registry_url }}' | base64 --decode` | tee -a openstack_rc.sh"
+            sh "echo export REG_USER=`oc get secrets openshift --template='{{ .data.registry_user }}' | base64 --decode` | tee -a openstack_rc.sh"
+            sh "echo export REG_PASSWORD=`oc get secrets openshift --template='{{ .data.registry_password }}' | base64 --decode` | tee -a openstack_rc.sh"
         }
 
         stage('cleanup HEAT environment') {
-            sh 'source ./openstack_rc.sh ; openstack stack show openshift-\$OS_TENANT_NAME && openstack stack delete openshift-\$OS_TENANT_NAME --wait --yes || echo stack not found'
+            sh 'source ./openstack_rc.sh ; openstack stack show openshift-\$OS_PROJECT_NAME && openstack stack delete openshift-\$OS_PROJECT_NAME --wait --yes || echo stack not found'
         }
 
         stage('setup host keys') {
@@ -75,6 +80,10 @@ node ('openstack-jenkins-slave') {
                 echo "  node_routes: \$NODE_ROUTES"                   >> environment.yaml
                 echo "  multinetwork: \$MULTINETWORK"                 >> environment.yaml
                 echo "  deploy_extra_gateway: \$DEPLOYEXTRAGATEWAY"   >> environment.yaml
+                echo "  registry_details:"                            >> environment.yaml 
+                echo "    registry_url: \$REG_URL"                      >> environment.yaml
+                echo "    registry_user: \$REG_USER"                    >> environment.yaml
+                echo "    registry_password: \$REG_PASSWORD"            >> environment.yaml
             ''')
             sh('cat environment.yaml')
             sh('cat rhel_reg_creds.yaml')
@@ -84,7 +93,7 @@ node ('openstack-jenkins-slave') {
         stage('Set variables HEAT deployment') {
             sh("""
                 source ./openstack_rc.sh;
-                openstack stack output show openshift-\$OS_TENANT_NAME bastion_ip -f value -c output_value > env.vars
+                openstack stack output show openshift-\$OS_PROJECT_NAME bastion_ip -f value -c output_value > env.vars
             """)
         }
 
@@ -153,14 +162,22 @@ node ('openstack-jenkins-slave') {
             """)
         }
 
-        slackSend color: 'good', message: "Pipeline build Completed Successfully: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
+        //slackSend color: 'good', message: "Pipeline build Completed Successfully: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
+
+
+       stage('Cleanup HEAT deployment on successful deployment') {
+            sh("""
+                source ./openstack_rc.sh;
+                openstack stack delete openshift-\$OS_PROJECT_NAME --wait --yes
+            """)
+        }
 
     } catch (e) {
         // If there was an exception thrown, the build failed
-        slackSend color: '#c2001f', message: "Pipeline failed :("
+        //slackSend color: '#c2001f', message: "Pipeline failed :("
         throw e
     } finally {
         // Success or failure, always send notifications
-        slackSend color: '#7ea8c8', message: "Pipeline finished"
+        // slackSend color: '#7ea8c8', message: "Pipeline finished"
     }
 }
